/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function GrassBlade(props) {
	const geometry = useGLTF("/models/grass_blade.glb");
	return (
		geometry
		// <mesh
		// 	{...props}
		// 	name="pPlane1"
		// 	castShadow
		// 	receiveShadow
		// 	geometry={nodes.pPlane1.geometry}
		// 	material={materials.lambert1}
		// 	position={[0, 0.005, 0]}
		// 	rotation={[-Math.PI, 0, 0]}
		// 	scale={0.01}
		// />
	);
}

useGLTF.preload("/models/grass_blade.glb");